services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    restart: always
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniominio
    ports:
      - 9000:9000
      - 9001:9001
    restart: always
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minio miniominio;
      /usr/bin/mc mb myminio/collabfile;
      /usr/bin/mc anonymous set public myminio/collabfile;
      exit 0;
      "
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - minio
    restart: always
    env_file:
      - .env
